app/Http/routes.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

# Tela de login
Route::get('/', ['as' => 'usuario.login', 'uses' => "Usuario\LoginController@login"]);
# Autenticação de usuário
Route::post('/auth', ['as' => 'usuario.auth', 'uses' => "Usuario\LoginController@auth"]);

// Somente para usuários autenticados
Route::group(['middleware' => 'auth.usuario'], function () {
	# Dashboard (área restrita)
	Route::get('/dashboard', ['as' => 'usuario.dashboard', 'uses' => "Usuario\DashboardController@dashboard"]);
});
// Somente para administradores
Route::group(['middleware' => 'auth.admin'], function () {
	# Rotas para administração de usuários (/profile) - somente administradores
	Route::resource('profile', "Usuario\ProfileController", ['except' => ['show', 'create', 'store']]);
});
// Todo mundo pode se cadastrar no sistema de login, mas não haverá opção de permissão administrativa
Route::resource('profile', "Usuario\ProfileController", ['only' => ['create', 'store']]);

Route::group(['middleware' => 'logout.usuario'], function () {
	# Logout (sair da sessão)
	Route::get('/logout', ['as' => 'usuario.logout', 'uses' => "Usuario\LogoutController@logout"]);
});

app/Models/ConfigAcessos.php
<?php

namespace EasyCMS\Models;

use Illuminate\Database\Eloquent\Model;

class ConfigAcessos extends Model
{
	/** @var string */
    protected $table = 'ConfigAcessos';
    
    /** @var string */
    protected $primaryKey = 'id';
    
    /** @var array */
    protected $fillable = [
    	'name', 'description',
    ];
    
    /** @var string */
    public $timestamps = false;
    
    /** @var string */
    public static $snakeAttributes = false;
}

app/Models/Usuario.php
<?php

namespace EasyCMS\Models;

use Illuminate\Foundation\Auth\User as Authenticatable;


class Usuario extends Authenticatable
{
	/** @var string */
    protected $table = 'Usuarios';
	
	/** @var string */
	protected $primaryKey = 'id';
	
	/** @var array */
	protected $fillable = [
		'name',
		'login',
		'email',
		'password',
		'remember_token',
		'status',
		'level',
	];
	
	/** @var array */
	protected $hidden = [ 'password', 'remember_token' ];
	
	/** @var bool */
	public $timestamps = false;
	
	/** @var boolean */
	public static $snakeAttributes = true;
}

app/User.php
<?php

namespace EasyCMS;

use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace EasyCMS\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesResources;

class Controller extends BaseController
{
    use AuthorizesRequests, AuthorizesResources, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/Usuario/DashboardController.php
<?php

namespace EasyCMS\Http\Controllers\Usuario;

use Illuminate\Http\Request;

use EasyCMS\Http\Controllers\Controller;
use EasyCMS\Http\Requests\Usuario\UsuarioRequest;

class DashboardController extends Controller
{
    /**
	* Acessa a dashboard (área restrita)
	*/
	public function dashboard(UsuarioRequest $request)
	{
		// recuperando dados do usuário logado
		$user = $request->user();
		
		if ($user){	
			// Mensagem de boas-vindas
			return view('usuario.home.dashboard')->with('usuario', $user);
		}
	}
}

app/Http/Controllers/Usuario/LoginController.php
<?php

namespace EasyCMS\Http\Controllers\Usuario;

use Illuminate\Http\Request;

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Input;
use EasyCMS\Http\Requests;
use EasyCMS\Http\Controllers\Controller;
use EasyCMS\Models\Usuario;

class LoginController extends Controller
{
	/**
	* Exibe a página inicial (home)
	*/
	public function login()
	{
		return view('usuario.home.home');
	}
	
	/**
	* Método para autenticar usuário
	*/
	public function auth(Request $request)
	{
		// credenciais de usuário
		$credenciais = Input::only('login', 'password');
		
		// redirecionar à home (/) login ou senha em branco
		if (empty($credenciais['login']) or empty($credenciais['password'])) {
			return redirect()->route('usuario.login')->with('error', 'Informe usuário e senha!');
		}
		
		$usuario = Usuario::where('login', $credenciais['login'])->first();
		
		// o usuário existe? caso negativo, login inválido: redirecionar à home (/)
		if (!$usuario){
			return redirect()->route('usuario.login')->with('error', 'Usuário inexistente!');
		}
		
		// a senha confere? Ok, prossiga
		if ( Auth::attempt($credenciais) ){
			# verifique se o usuário está inativo
			if ( !$usuario->status ){
				return redirect()->route('usuario.login')->with('error', 'Usuário inativo não pode autenticar!');
			}
		
			# neste momento, todos os testes passaram; então, é só redirecionar à dashboard (área restrita)
			return redirect()->route('usuario.dashboard');
		}
		
		// a senha não confere? redirecionar à home (/)
		return redirect()->route('usuario.login')->with('error', 'Falha na autenticação!');
	}
}

app/Http/Controllers/Usuario/LogoutController.php
<?php

namespace EasyCMS\Http\Controllers\Usuario;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use EasyCMS\Http\Requests;
use EasyCMS\Http\Controllers\Controller;

class LogoutController extends Controller
{
    /**
	* Logout (sair da sessão)
	*/
	public function logout(Request $request)
	{
		// somente se o usuário estiver logado, 
		if (Auth::check()) {
			Auth::logout();									# fazer o logout
			return redirect()->route('usuario.login');		# redirecionando para a home (/)
		}
	}
}

app/Http/Controllers/Usuario/ProfileController.php
<?php

namespace EasyCMS\Http\Controllers\Usuario;

use Illuminate\Http\Request;

use EasyCMS\Http\Requests;
use EasyCMS\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use EasyCMS\Models\Usuario;
use EasyCMS\Http\Requests\Usuario\ProfileRequest;
use Illuminate\Http\JsonResponse;
use EasyCMS\Repositories\Concretes\Repository\ProfileRepository;

class ProfileController extends Controller
{
	/** @var ProfileRepository */
	protected $profileRepository;
	
	/**
	 * ProfileController's default constructor.
	 * @param ProfileRepository $profileRepository
	 */
	public function __construct(ProfileRepository $profileRepository) {
		$this->profileRepository = $profileRepository;
	}
	
	
	/**
	 * Lista todos os usuários cadastrados. Apenas adminsitradores podem visualizar.
	 */
	public function index()
	{
		#listagem simples de usuários
		$return = $this->profileRepository->listAllUsers();
		return new JsonResponse($return);
	}
	
	
	/**
	 * Exibe o formulário de cadastro.
	 */
	public function create()
	{
		// TODO: formulário de registro (link "Sign up" ou "Register")
		$levels = [
			1 => 'Usuário comum',
			2 => 'Gestor',
			3 => 'Sys Admin',
		];
		
		return view('usuario.profile.create.index', compact('levels'));
	}
	
	/**
	 * Faz o cadastro de usuários. Apenas administradores podem acessar o recurso.
	 * @param Request $request
	 */
	public function store(ProfileRequest $request)
	{
		# dados de usuário
		$dados = $request->all();
		
		# enviando o usuário recém-criado
		$result = $this->profileRepository->create($dados);
		return new JsonResponse($result);
	}
	
	
	/**
	 * Exibe o formulário de edição. Apenas administradores podem visualizá-lo.
	 * @param Request $request
	 * @param integer $id
	 */
	public function edit(Request $request, $id)
	{
		
	}
	
	/**
	 * Faz a atualização de usuários. Apenas administradores podem acessar o recurso.
	 * @param Request $request
	 * @param integer $id
	 */
	public function update(ProfileRequest $request, $id)
	{
		# dados de usuário
		$dados = $request->all();
		
		# retornando os dados de usuário, atualizados
		$return = $this->profileRepository->update($id, $dados);
		return new JsonResponse($return);
		
	}
	
	/**
	 * Exclui cadastro de usuário que não tenha artigos associados. Apenas administradores têm acesso ao recurso. 
	 * @param integer $id
	 */
	public function destroy($id)
	{
		# TODO: verificação de artigos publicados
		
		$result = $this->profileRepository->delete($id);
		return new JsonResponse($result);
	}
	
}

resources/views/usuario/home/dashboard.blade.php
<!doctype html>
<html lang="en">
<head>
	<meta charset="UTF-8" />
	<title>Área restrita</title>
</head>
<body>
	<h1>Bem-vindo, {{ $usuario->name }}!</h1>
	<p style="text-align: right;">
		@if ( $usuario->level == 3 )
		<a href="{{ route('profile.index') }}">Profile</a> |
		@endif
		<a href="{{ route('usuario.logout') }}">Sair</a>
	</p>
</body>
</html>

resources/views/usuario/home/home.blade.php
<!doctype html>
<html lang="en">
<head>
	<meta charset="UTF-8" />
	<title>Home page</title>
</head>
<body>
	<h1>Login</h1>
	
	<!-- Mensagem de erro -->
	@if ( Session::has('error') )
	<p style="color: red;">
		Erro: {{ Session::get('error') }}
	</p>
	@elseif ( Session::has('alert') )
	<p style="color: #d28420;">
		Atenção: {{ Session::get('alert') }}
	</p>
	@endif
	
	<form action="{{ route('usuario.auth') }}" method="post">
		{{ csrf_field() }}
		<label for="inputLogin">
			Login: <input type="text" id="inputLogin" name="login" autofocus />
		</label>
		<label for="inputSenha">
			Senha: <input type="password" id="inputSenha" name="password" />
		</label>
		<button type="submit">Login</button>
	</form>
	
	<a style="display: inline-block; float: right;" href="{!! route('profile.create') !!}">Sign up</a>
	
</body>
</html>

resources/views/usuario/profile/create/index.blade.php
<!doctype html>
<html lang="en">
<head>
	<meta charset="UTF-8" />
	<title>Register</title>
</head>
<body>
	<h1>Sign up</h1>
	
	<!-- Mensagem de erro -->
	@if ( Session::has('error') )
	<p style="color: red;">
		Erro: {{ Session::get('error') }}
	</p>
	@elseif ( Session::has('alert') )
	<p style="color: #d28420;">
		Atenção: {{ Session::get('alert') }}
	</p>
	@endif

	<form method="post" action="{!! route('profile.store') !!}">
		{!! csrf_field() !!}
		<label for="inputName">
			Nome: <input type="text" id="inputName" name="name" autofocus />
		</label>
		<br />
		<label for="inputLogin">
			Login: <input type="text" id="inputLogin" name="login" />
		</label>
		<br />
		<label for="inputEmail">
			Email: <input type="email" id="inputEmail" name="email" />
		</label>
		
		<br />
		
		<label for="inputSenha">
			Senha: <input type="password" id="inputSenha" name="password" />
		</label>
		<!-- <br />
		<label for="inputSenhaConfirm">
			Confirmar Senha: <input type="password" id="inputSenhaConfirm" name="password" />
		</label> -->
		<br />
		<label for="selectLevel">
			Nível de acesso: <br />
			<select name="level">
				@foreach($levels as $level => $desc)
				{-- o usuário é administrador? criar opção *admin* --}
					@if ( $level < 3 )
					<option value="{{ $level }}">{{ $desc }}</option>
					@endif
				@endforeach
			</select>
		</label>
		
		<br />
		
		<button type="submit">Sign up</button>
	</form>
	
	@include('usuario.profile.create.js')
</body>
</html>

resources/views/usuario/profile/create/js.blade.php
<script>
	(function(){
		// TODO: javascript para comparar as senhas
	})();
</script>

resources/views/usuario/profile/edit/index.blade.php
{-- TODO: formulário de atualização de dados cadastrais. Apenas administradores podem visualizá-lo --}

resources/views/usuario/profile/index/index.blade.php
{-- TODO: formulário de listagem. Apenas administradores podem visualizá-lo --}